### ISSUE TITLE
leancloud 报错了

### ISSUE THREAD

**Issue by caimaoy** [ahjsrhj/workflow-upimage#1]
我没有看过 `leancloud` 的文档，可能返回的结构不是这样

```
16:22:11 connectionpool.py:393 DEBUG    https://api.leancloud.cn:443 "GET /1.1/classes/image?order=-createdAt&redirectByAPI=e1 HTTP/1.1" 404 None
16:22:11 workflow.py:2074 ERROR    u'results'
Traceback (most recent call last):
  File "/Users/caimaoy/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.A5BCDD4D-A49A-4875-8CA9-34170C212D05/workflow/workflow.py", line 2067, in run
    func(self)
  File "main.py", line 108, in main
    get_img_list(wf)
  File "main.py", line 42, in get_img_list
    img_list = leancloud.get_list(wf)
  File "/Users/caimaoy/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.A5BCDD4D-A49A-4875-8CA9-34170C212D05/leancloud.py", line 71, in get_list
    return result[u'results']
KeyError: u'results'
```

**Comment by ahjsrhj** [comment]
sorry，写文档的时候遗漏了，你需要在`leancloud`上创建一个项目，在这个项目里创建一个名为`image`的class,
![1549781249729.png](https://i.loli.net/2019/02/10/5c5fc90333bb5.png)
之后在这个项目的设置里获取`appkey`和`appid`
还有就是不知道会不会有影响，我的`leancloud`节点选择的是`中国华东节点`，不确定其它节点的api是否是一致的。。

**Comment by caimaoy** [comment]
我没有创建，调用 api 之后他帮我创建了，之前是会抽风（不知道是不是服务端的问题），现在好像已经好了，我也是同一个节点

**Comment by ahjsrhj** [comment]
好的，我抽空再清空数据测试一下。。
